name: .NET CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore AssociationC.sln

      - name: Build
        run: dotnet build AssociationC.sln --no-restore --configuration Release
  tests:
   runs-on: ubuntu-latest

   needs: build

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Set up .NET Core SDK
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '8.0.x'

     - name: Cache .NET packages
       uses: actions/cache@v3
       with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
         restore-keys: |
           ${{ runner.os }}-nuget-

     - name: Restore dependencies
       run: dotnet restore AssociationC.sln

     - name: Run Unit Tests
       run: dotnet test AssociationC.sln --filter FullyQualifiedName~Domain.Tests --configuration Release

     - name: Run Integration Tests
       run: dotnet test AssociationC.sln --filter FullyQualifiedName~IntegrationTests --configuration Release

     - name: Upload Integration Test Results
       uses: actions/upload-artifact@v3
       with:
         name: test-results
         path: test-results/


